### PR TITLE
Added Skeleton and basic script for running the test cases

### PR DESCRIPTION
**Pull request by atiqsayyed**
I've removed the xht documents from test/resources..

if you want to run the test cases, add the xhtml folder from nightly-unstable to test/resouces

we can iterate over it and make it much more fast and better...

### CODE REVIEW

**Comment by hrj** [comment]
Awesome, thanks!

There are 3 big files in this commit, hence github can't show them:

```
src/test/resources/test-cases.xml
src/main/resources/reftest-toc.xml
src/main/resources/test-cases.xml
```

Can you please describe them?

**Comment by atiqsayyed** [comment]
src/main/resources/reftest-toc.xml : this is the index file which we parse, http://test.csswg.org/suites/css2.1/nightly-unstable/xhtml1/reftest-toc.xht

src/main/resources/test-cases.xml :  after parsing the reftest-toc.xml we generate test-cases.xml which is our required format which we use it for running test cases

src/test/resources/test-cases.xml, rc/main/resources/test-cases.xml (both are same xmls)

**Comment by hrj** [comment]
I think these should not be in the repo. I could do the changes myself, but
1. The repo will grow big if I delete it later. It needs to be removed in the first commit itself.
2. I want you to get the credit for the commits. So it is better if you do it, and then create a new rebased / squashed branch.

**Comment by atiqsayyed** [comment]
I've made the changes.... We'll talk about the implementation details and how we want to take it further

**Comment by hrj** [comment]
Cool, thanks! I see that you have committed to master, making it difficult to rebase.

I will rebase it myself and credit you.

**Comment by hrj** [comment]
I have rebased and merged with master, retaining the authorship.

**Pull request closed without merging**
